### ISSUE TITLE
2ed forum Not working

### ISSUE THREAD

**Issue by NFLD99** [Iku/Google-Forms-to-Discord#10]
Hello, i got this script to work on one of my forums but when i made a new one (new webhook ofc) it seems to not get the submits, i followed the exact steps i did on the first one the only things being different are the forums, Webhook url and title/footer.

thank you for your time, any help is greatly appreciated.

**Comment by NFLD99** [comment]
Fixed it.
Had to remove the option to use check boxes on the forum

**Comment by Iku** [comment]
you can use options, just not check boxes theres no way for the script to handle it sadly
