### ISSUE TITLE
Get the response object instead of sending the message

### ISSUE THREAD

**Issue by Rage-cmd** [Iku/Google-Forms-to-Discord#101]
First of all, I am very grateful for your contribution and would like to thank you for that. This code works fine for me but the project in which I am working requires me to create a google calendar event based on the form response. I can achieve this using google sheets but that can consume a lot of time as my project scales up. This code sends a embed message to the channel, but what I want currently is to obtain a python dictionary/JSON object response so that I can use it to create a google event using discord.py. Is this possible? I apologize if I said something which doesn't makes sense as I am new to this domain.

**Comment by Kelo** [comment]
If you're wanting to create the event from a form response, you can 100% do this. You just need to build a json structure from the response collected and either create the event from inside the response or send it to the script/app that will create the event from the response

**Comment by Rage-cmd** [comment]
Thank you for replying. I get your point that I can directly create an event in the Apps script editor. But I want to go with the second solution you proposed but I am not sure how to receive this data into a python app(I am new to web development). I am sorry if it looks like a question to be asked on stackoverflow.
