### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by DivyeshSubash** [Iku/Google-Forms-to-Discord#115]
After pasting the code ( image )( I only paste the string part ) I still get an error ( string error )

![Screenshot 2021-11-26 212743](https://user-images.githubusercontent.com/85064025/143588246-063c2975-8be3-4328-aa73-c22c28e9bfd4.png)

**Comment by Kelo** [comment]
My guess would be that you've missed a comma at the end of the previous line.

BTW,  this repo isn't actively maintained anymore. I'd suggest checking out a more recent fork.

**Comment by DivyeshSubash** [comment]
> My guess would be that you've missed a comma at the end of the previous line.
> 
> BTW, this repo isn't actively maintained anymore. I'd suggest checking out a more recent fork.

I finally realize about the comma just yesterday 😂

btw I tried using your repo ( it worked, Thank you !! )
