### ISSUE TITLE
help

### ISSUE THREAD

**Issue by louisplayzz** [Iku/Google-Forms-to-Discord#116]
![image](https://user-images.githubusercontent.com/96347019/146678995-ae7b4435-d304-4d65-a1ae-5c3519e3edcb.png)

this problem

**Comment by Kelo** [comment]
If you paste in your code, it would help to debug it

**Comment by louisplayzz** [comment]
var POST_URL = "https://discord.com/api/webhooks/922136052746035241/e2kgfSi34firopDHuVU_7qP8fUjgAk2GUg3P8tNHuTGQsQZfi5l6HBRttuXsiqwMcPVr";

function onSubmit(e) {
    var form = FormApp.getActiveForm();
    var allResponses = form.getResponses();
    var latestResponse = allResponses[allResponses.length - 1];
    var response = latestResponse.getItemResponses();
    var items = [];

    for (var i = 0; i < response.length; i++) {
        var question = response[i].getItem().getTitle();
        var answer = response[i].getResponse();
        try {
            var parts = answer.match(/[\s\S]{1,1024}/g) || [];
        } catch (e) {
            var parts = answer;
        }

        if (answer == "") {
            continue;
        }
        for (var j = 0; j < parts.length; j++) {
            if (j == 0) {
                items.push({
                    "name": question,
                    "value": parts[j],
                    "inline": false
                });
            } else {
                items.push({
                    "name": question.concat(" (cont.)"),
                    "value": parts[j],
                    "inline": false
                });
            }
        }
    }

    var options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        },
        "payload": JSON.stringify({
            "content": "‌",
            "embeds": [{
                "title": "louisplayz staff forms",
              "color": 33023, // This is optional, you can look for decimal colour codes at https://www.webtoolkitonline.com/hexadecimal-decimal-color-converter.html
                "fields": items,
                "footer": {
                    "text": "louisplayz"
                }
            }]
        })
    };

**Comment by Kelo** [comment]
I think it's something to do with your trigger options. You should double check them - BTW you'll need to reset your webhook url

**Comment by louisplayzz** [comment]
i know i need to reset

**Comment by louisplayzz** [comment]
it works now
