### ISSUE TITLE
Code Incomplete / Untested

### ISSUE THREAD

**Issue by Batimius** [Iku/Google-Forms-to-Discord#120]
# Introduction 

This is simply an issue regarding the entire code and why it doesn't work for most people. Let us first look at the code itself:

```js
const POST_URL = "WEBBHOOK URL";

function onSubmit(e) {
    const response = e.response.getItemResponses();
    let items = [];

    for (const answer of response) {
        const question = answer.getItem().getTitle();
        const answer = answer.getResponse();
        
        try {
            const parts = answer.match(/[\s\S]{1,1024}/g) || [];
        } catch (e) {
            const parts = answer;
        }

        if (!answer) {
            continue;
        }
        
        for (const part of parts) {
            if (j == 0) {
                items.push({
                    "name": question,
                    "value": part,
                    "inline": false
                });
            } else {
                items.push({
                    "name": question.concat(" (cont.)"),
                    "value": part,
                    "inline": false
                });
            }
        }
    }

    const options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        },
        "payload": JSON.stringify({
            "content": "‌",
            "embeds": [{
                "title": "Some nice title here",
              "color": 33023, // This is optional, you can look for decimal colour codes at https://www.webtoolkitonline.com/hexadecimal-decimal-color-converter.html
                "fields": items,
                "footer": {
                    "text": "Some footer here"
                }
            }]
        })
    };

    UrlFetchApp.fetch(POST_URL, options);
};
```

After going through and fixing each issue step by step and testing it out, I found all the issues that one could encounter by solving each issue individually step by step.

# Issues

### Problem
The first issue comes from the variable naming. At the very start, we see `const answer` being defined in the for-loop. Just two lines after, `const answer` is re-defined in the loop, making the code completely ignore the first `answer` in the for-loop and giving the `Cannot access 'answer' before initialization at onSubmit(Code:8:26)` error.

### Solution
There are many ways to solve this, but I'll give the two simple ones. The simple solution pattern will repeat with the ones below as well.
1) Instead of making `answer` a constant, make it a  let so it can be reassigned. Since you are assigning it once again in the bottom, you may as well make it reassignable. Example:
```js
for (let answer of response) {
    const question = answer.getItem().getTitle();
    answer = answer.getResponse();
```
2) Instead of naming the constant inside the for-loop `answer`, name it something else and reference it later. This would be ideal if you **really** do not want it to be changeable, but if you don't care, I highly recommend using the first solution instead, although this one is good practice overall. Example:
```js
for (const responseAnswer of response) {
    const question = responseAnswer.getItem().getTitle();
    const answer = responseAnswer.getResponse();
```

### Problem
Const variables have a block scope. That being said, both part declarations are simply disregarded. This can also be confirmed while looking at the [W3Schools page about JavaScript Const](https://www.w3schools.com/js/js_const.asp).

### Solution
1) Define an empty let variable outside of the try statement and assign it to whatever value it needs to be assigned. Example:
```js
let parts = []

try {
    parts = answer.match(/[\s\S]{1,1024}/g) || [];
} catch (e) {
    parts = answer;
}
```
2) Change the variable from a const to a var. I really do not recommend this since it creates a global scope and that isn't good practice. Example:
```js
try {
    var parts = answer.match(/[\s\S]{1,1024}/g) || [];
} catch (e) {
    var parts = answer;
}
```

### Problem
The old code used a for-loop with a variable named `j` which was used to iterate throughout the parts. This does not happen no more, so the variable `j` simply doesn't exist.

### Solution
1) Iterate through the entries instead of just the values of the array. This will also give you the index which you can use to check if it is the first value or not. Example:
```js
for (const [index, part] of Object.entries(parts)) {
    if (index == 0) {
        items.push({
            "name": question,
            "value": part,
            "inline": false
        });
    } else {
        items.push({
            "name": question.concat(" (cont.)"),
            "value": part,
            "inline": false
        });
    }
}
```
2) Use the `Array.findIndex()` function. I do not even recommend this solution since it is resource-hungry and there is no need for it. No example code for this one.

### Problem
This issue can occur for many reasons, but it usually is because of an invalid webhook body. The most common examples are names / fields being too large (which usually isn't the case because the script limits the descriptions) or invalid colors.

### Solution
This problem is a per-person problem. I recommend using discohook when choosing a color and from there copying the color code and pasting it. There aren't many recommendations I can give and nor is this a code-related issue.

# Conclusion

As seen above, the current code on the repository is incomplete and untested. It seems like an attempt to make the old code more efficient but by doing so, it was made unstable and was not tested. I personally never really used this code and had made my own for customization, but since this is the go-to for anyone who does not know coding, it is unacceptable for such errors to be existent, especially considering that the creator has yet to solved them. It is also especially outrageous that the previous code was working fine and as intended and this new incomplete and untested code replaced the stable and working one.

If you are currently in need of an actual working code, you can use the previous version or use the corrected one. Here is the corrected one (which as been checked and tested multiple times in order to ensure that it works):
```js
const POST_URL = "WEBBHOOK URL";

function onSubmit(e) {
    const response = e.response.getItemResponses();
    let items = [];

    for (const responseAnswer of response) {
        const question = responseAnswer.getItem().getTitle();
        const answer = responseAnswer.getResponse();
        let parts = []

        try {
            parts = answer.match(/[\s\S]{1,1024}/g) || [];
        } catch (e) {
            parts = answer;
        }

        if (!answer) {
            continue;
        }

        for (const [index, part] of Object.entries(parts)) {
            if (index == 0) {
                items.push({
                    "name": question,
                    "value": part,
                    "inline": false
                });
            } else {
                items.push({
                    "name": question.concat(" (cont.)"),
                    "value": part,
                    "inline": false
                });
            }
        }
    }

    const options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        },
        "payload": JSON.stringify({
            "content": "‌",
            "embeds": [{
                "title": "Some nice title here",
              "color": 33023, // This is optional, you can look for decimal colour codes at https://www.webtoolkitonline.com/hexadecimal-decimal-color-converter.html
                "fields": items,
                "footer": {
                    "text": "Some footer here"
                }
            }]
        })
    };

    UrlFetchApp.fetch(POST_URL, options);
};
```

I personally find it unacceptable that such code was released and overwrote a working one. If you are the owner of the repository and are reading this, please, for the love of what is holy, fix the errors on the code by either copying this code, implementing the solutions suggested or solving them with your approaches, and when you are about to publish an update, please test it out on Google Forms and ensure that it works before publishing and overwriting the already working existing code. I am a programmer so I know how to solve these issues, but most people who use the script don't.

That is all. Hopefully this helped anyone who was lost and did not know why their script wasn't working.

**Comment by Kelo** [comment]
Hi.

I've mentioned this in a couple of other issues; but this repo isn't actively maintained by the owner anymore. If you feel you can do a better job then feel free to create a fork as I have done.

Thanks for putting this together, I too encountered the same bugs and errors you mentioned & had to fix them in my fork. 
Unfortunately this will only reach those who really use GitHub and know to view other's issues.

>I personally find it unacceptable that such code was released and overwrote a working one.

This is pretty standard in open source. Especially when it's one individual doing the maintaining.

**Comment by Iku** [comment]
merged your code, i am far to busy to take a look/maintain this repository properly anymore.  sorry for not fully testing the other merge out.

**Comment by Batimius** [comment]
> merged your code, i am far to busy to take a look/maintain this repository properly anymore. sorry for not fully testing the other merge out.

Glad to hear that you merged it. I do understand that you are busy, I too am very busy, but I just didn't understand why you pushed code that wasn't fully tested. That being said though, I am glad you looked and corrected your mistake, and I'm sure many others also appreciate that as well.

**Comment by Zombiefiedgamingyt** [comment]
Mar 11, 2022, 5:41:42 PM	Error	Exception: Request failed for https://discord.com returned code 400. Truncated server response: {"embeds": ["0"]} (use muteHttpExceptions option to examine full response)
    at onSubmit(d.hs:57:17)

**Comment by Batimius** [comment]
> Mar 11, 2022, 5:41:42 PM Error Exception: Request failed for https://discord.com returned code 400. Truncated server response: {"embeds": ["0"]} (use muteHttpExceptions option to examine full response) at onSubmit(d.hs:57:17)

That is probably because you provided an invalid body. Unfortunately, it isn't easy to track why this doesn't work. I recommend you output the JSON being sent and try putting it through a website like [discohook.com](https://discohook.org/), so you can see why it doesn't work. Like I mentioned in my reply above, this is a self-driven error, not one caused by this code.

> Error Exception: Request failed for https://discord.com/ returned code 400. Truncated server response: {"embeds": ["0"]} (use muteHttpExceptions option to examine full response) at onSubmit(Code:57:17)
> Problem
> This issue can occur for many reasons, but it usually is because of an invalid webhook body. The most common examples are names / fields being too large (which usually isn't the case because the script limits the descriptions) or invalid colors.

> Solution
> This problem is a per-person problem. I recommend using discohook when choosing a color and from there copying the color code and pasting it. There aren't many recommendations I can give and nor is this a code-related issue.

Most of the times, it is caused because of the color setting in the embed, but it could be other reasons. Try to see why that is.

C.C.: @Zombiefiedgamingyt
