### ISSUE TITLE
TypeError: Cannot read property 'response' of undefined onSubmit	@ Code.gs:4

### ISSUE THREAD

**Issue by Aryancooldude** [Iku/Google-Forms-to-Discord#127]
![image](https://user-images.githubusercontent.com/91192691/170242860-15105f08-6a34-47e7-8886-ac7f7d09baf1.png)

**Comment by Kelo** [comment]
Not sure if you managed to fix this issue, but I believe it's due to you trying to run the code without any responses being there.

You need to setup the trigger and submit a response to test the webhook properly.

**Comment by gBloxxed** [comment]
> 

It still doesn't work and shows the same error.

**Comment by AskoPoss** [comment]
Ups, aynı hata ile karşılaştım
