### ISSUE TITLE
TypeError: Cannot call method "getItemResponses" of undefined. at onSubmit(Code:4)

### ISSUE THREAD

**Issue by infinityloop** [Iku/Google-Forms-to-Discord#13]
I saw that two people submitted the error while trying to run the form, but I'm getting this error from submitting my form.

My event object looks like this:
{"triggerUid":"57383","source":"Form","authMode":"FULL"}

I've also tried going through the source object and using getResponses(), but I get the following error: 
You do not have permission to call Form.getResponses. Required permissions: (https://www.googleapis.com/auth/forms.currentonly || https://www.googleapis.com/auth/forms) at onSubmit(Code:5)

Is there any special permissions I need to access the responses? I'm the owner of the Google Form.

**Comment by AlexJFox** [comment]
Same issue

**Comment by untuned** [comment]
Same here, maybe a change in the Google API?

**Comment by Iku** [comment]
this is a known issue, but i have no idea what is causing it and I've been a bit busy with life to sit and look at the api and figure it out, if someone would like to take a crack at it, it should be a fairly simple solution.

**Comment by Iku** [comment]
this is a weird workaround but should work. if you want to make a pull request i can merge this if you would like to be labled as a contributer.

**Comment by AlexJFox** [comment]
It's not my fix so I don't want to be labelled as supplying it, I'll try and find where I got the solution from so I can credit, I can still do the PR if you wish

**Comment by Iku** [comment]
fixed. pushed and good to go
