### ISSUE TITLE
No support for check boxes

### ISSUE THREAD

**Issue by DeveloperBoy** [Iku/Google-Forms-to-Discord#15]
Hello,

The code has no support for check boxes. When I try to use checkboxes, I get an error:
`TypeError: Can't find function match in object Computer's. (row 13, file 'Code')`

A screen of the debugreporter:
[Click on this](https://prnt.sc/ljadn2)

Kind regards,

Stijn - SBDeveloper

**Comment by Blizzard098** [comment]
I too am having this issue.

**Comment by Iku** [comment]
this has already been addressed in the original issue #5
