### ISSUE TITLE
Error Running Script

### ISSUE THREAD

**Issue by Jerry12798** [Iku/Google-Forms-to-Discord#21]
I'm getting "Script function not found: myFunction"... it may be because I didn't add triggers because quite frankly I'm not sure what they are. I'm also curious if this script runs 24/7 or if it needs to be added to a Bot?

**Comment by Jerry12798** [comment]
Got the script to work. Now if I want it to post in not just one Channel but also another one how would I add this into the script? Would it be something like ```UrlFetchApp.fetch(POST_URL, options)
UrlFetchApp.fetch(POST_URL_2, options)```

**Comment by austinhuang0131** [comment]
Yes.
