### ISSUE TITLE
Pictures on readme are dead

### ISSUE THREAD

**Issue by austinhuang0131** [Iku/Google-Forms-to-Discord#23]
2 pics about trigger

I mean I still figured it out but there may be people who didn't

**Comment by Iku** [comment]
as im currently dealing with my mother being in the hospital I do not have to time fix this, if you would like to fix the readme and upload a pull request i would be happy to merge it

**Comment by RobinSchapendonkGames** [comment]
m2 problems if i open them i always get the error

Error Fetching Resource
