### ISSUE TITLE
Can't get it to to work

### ISSUE THREAD

**Issue by Zxtori** [Iku/Google-Forms-to-Discord#24]
i made the google script and trigger and did a test response and it did not work i correctly made the web hook but it just doesn't work.

**Comment by codeinteger6** [comment]
Have you replaced `WEBHOOKURL` at the top of the script with your webhook URL? Also try these settings when creating a new trigger.

![trigger settings](https://raw.githubusercontent.com/codeinteger6/files/master/images/trigger.jpg)

**Comment by KiTTYsh** [comment]
We need more information to be of assistance.

Please:
1. Go to the script editor from your form
2. Go to Edit > Current Project's Triggers
3. At the far right of your trigger, click the dot-dot-dot menu, and select "Failed Executions"
4. Click on a failed execution to get the error log, and post it here.  Ensure that your webhook URL is redacted if it is contained within the error.
