### ISSUE TITLE
Form Script Error 

### ISSUE THREAD

**Issue by Dakesoul** [Iku/Google-Forms-to-Discord#34]
Getting the below error from the script. It works fine for one form, but doesn't for another;

Request failed for https://discordapp.com/api/webhooks/xxxxxxxxxxxx returned code 400. Truncated server response: {"embeds": ["0"]} (use muteHttpExceptions option to examine full response). (line 52, file "Code")

I don't have any # in my form, so unsure what's causing the issue. I have no coding experience, so not able to figure it out. :(

**Comment by Dakesoul** [comment]
Line 52 is;

    UrlFetchApp.fetch(POST_URL, options);

**Comment by Akanixon** [comment]
I'm having the same problem. any suggestions on how to fix it?

![image](https://user-images.githubusercontent.com/22319382/63270255-1d114780-c298-11e9-814e-ef93e582a1e9.png)

**Comment by DashieSystems** [comment]
I seem to be getting the same error too. Have you found a fix for it?

**Comment by gman1230321** [comment]
Same
This seems to be a common problem

**Comment by AaronFarrow** [comment]
same here, but it happened after a week of working properly.

**Comment by Vanzman** [comment]
Has any solution been found for this yet?
