### ISSUE TITLE
Embedding images from form upload

### ISSUE THREAD

**Issue by nick-chin** [Iku/Google-Forms-to-Discord#37]
Is there a way to embed uploaded images into the webhook? For example, someone can upload an image into a form, and I would like that to be embedded in the webhook post. However, the current script will give a string output of the image, something like this:

**Upload Image if Applicable**
1yQrFMA8gDU64QA6julWg8GdigNN5fY-Y
**Where is this event happening?**
some location
**When is this event occurring or application due? If there are multiple dates, please use the earliest one.**
2019-09-12
**Application link or Contact info**
some link
**Description of Event or Application**
testing description of what an application/event would look like.

Does anyone know how one could embed the image?

**Comment by sharpnd** [comment]
Hi there, did you get this figured out?

**Comment by nick-chin** [comment]
> Hi there, did you get this figured out?

@sharpnd nope i never did, i believe i chose a different implementation for my use case without google forms

**Comment by sharpnd** [comment]
> > Hi there, did you get this figured out?
> 
> @sharpnd nope i never did, i believe i chose a different implementation for my use case without google forms

Thanks for the info!
