### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by lotnikPL** [Iku/Google-Forms-to-Discord#38]
Hi
I follow with these steps in README and I think I configured it right.
But it doesn't work...
I'm new at programming so maybe I can't see the problem.
Some screenshots in attachments.
![photo](https://user-images.githubusercontent.com/53975526/62823680-df276b80-bb93-11e9-911f-b5680857667f.png)
![photo2](https://user-images.githubusercontent.com/53975526/62823681-e189c580-bb93-11e9-9534-c0a99762d9ed.png)
![photo3](https://user-images.githubusercontent.com/53975526/62823705-201f8000-bb94-11e9-9171-757232b9f089.png)

**Comment by codeinteger6** [comment]
Did you try submitting a response on your Google form?

**Comment by lotnikPL** [comment]
Yes I tried

**Comment by bob432626** [comment]
i am having the same problem
