### ISSUE TITLE
Request failled | returned code 400 | Truncated server response: {"embeds": ["0"]}

### ISSUE THREAD

**Issue by Akanixon** [Iku/Google-Forms-to-Discord#39]
As stated above I am getting this failures:
![image](https://user-images.githubusercontent.com/22319382/63271206-eccaa880-c299-11e9-8c08-00f15405c8a7.png)

Code:
![image](https://user-images.githubusercontent.com/22319382/63271411-619de280-c29a-11e9-88da-b8c9d62acc96.png)

**Comment by Akanixon** [comment]
Found the problem.
Error occurs because I got some optional fields that can be empty

**Comment by sahansk2** [comment]
@tayedenae 
You have to check that the optional field is empty. Wrapping the `items.push` statement in an if-block will fix it. Something like:

```
if (parts[j]) {
    items.push({ /* stuff */ })
}
```
