### ISSUE TITLE
Request fails every time it runs

### ISSUE THREAD

**Issue by ImRodry** [Iku/Google-Forms-to-Discord#40]
I've been getting the following message every time the script runs 
![image](https://user-images.githubusercontent.com/38259440/64925297-3dc0b480-d7e6-11e9-8ab3-054b11ebd651.png)

**Comment by matthewthemiller** [comment]
I was going to ask something similar. Any solutions for this? Or is it related to a poor response the regex didn't pickup?
```
Request failed for https://discordapp.com returned code 400. Truncated server response: {"message": "Cannot send an empty message", "code": 50006} (use muteHttpExceptions option to examine full response) (line 53, file "code2")
```
