### ISSUE TITLE
Missing } after property list. (line 44, file "Code")

### ISSUE THREAD

**Issue by Rmarmorstein** [Iku/Google-Forms-to-Discord#42]
I keep getting this error: 

Missing } after property list. (line 44, file "Code")

**Comment by ts3sports** [comment]
Any word on this fix? I am having the same issue

**Comment by Rmarmorstein** [comment]
I made a pull request. It is an easy fix, you should be able to find the
changes I made in that commit.

**Comment by Iglum** [comment]
Strange, i have the same problem evev with the changes.

**Comment by Rmarmorstein** [comment]
Use this change:
https://github.com/Rmarmorstein/Google-Forms-to-Discord/commit/e415e4b3c077025cceac4044e625407016b79148

**Comment by mat-pandaz** [comment]
change 

var options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        }

to

var options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        },

added coma at the end.
