### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wc3717** [Iku/Google-Forms-to-Discord#44]
![E6986F69-1291-4529-831C-5375D59F3DF9](https://user-images.githubusercontent.com/22899241/69506791-3e16c200-0f84-11ea-9cd4-4f7e39dd28f3.png)

**Comment by MrPrince3rd** [comment]
I'm having the same problem.  The script was working the other day, but now all it returns is this error.

**Comment by saimoyi** [comment]
Same issue here also questioned this within Discord API channel, they've said 
"Discord fixed an issue where they were incorrectly ignoring content headers. You must now properly specify the content type. If must now specify:
Content-Type: application/json"

**Comment by saimoyi** [comment]
nvm found answer in https://github.com/Iku/Google-Forms-to-Discord/issues/42

Add inbetween 

> "method": "post",

> "payload": JSON.stringify({
>             "embeds": [{

this

> "headers": {
>         "Content-Type": "application/json",
>       },
