### ISSUE TITLE
Script Fails When Syntax Errors Fixed

### ISSUE THREAD

**Issue by AMereBagatelle** [Iku/Google-Forms-to-Discord#45]
Me and another person are having the same error.  The error comes when we fix the syntax error by getting rid of the
"headers": {
        "Content-Type": "application/json",
}
and as soon as we remove these, the script compiles correctly but when tested it has a error of this:
![image](https://user-images.githubusercontent.com/56981737/69833330-12ecd680-1201-11ea-831b-e0cfe6f3d37e.png)

**Comment by 3GaNwO** [comment]
I have updated my script and I am still getting this same error! what else can be causing this error?
