### ISSUE TITLE
Syntax Error on line 44 fixed: solution included

### ISSUE THREAD

**Issue by IAmNotCreative21** [Iku/Google-Forms-to-Discord#46]
Include a comma on line 45 after the curly bracket
![unknown](https://user-images.githubusercontent.com/33880710/69844655-2ddc3c80-123b-11ea-85e8-c4075448e59d.png)

**Comment by Jadfer** [comment]
THANKYOU!

**Comment by aXBlackDeathXa** [comment]
I recommend the following change.
[https://i.imgur.com/Vs9ZbW2.png](url)

**Comment by 3GaNwO** [comment]
I have done this change and I am still getting the same error :( 

Also I only have 56 lines in this script but I see the img has 58? Am I missing something else? 

I have used the updated js that is included and added the , as shown above and still on 56 lines and not 58 lines and it still has the same errors

**Comment by Iku** [comment]
fixed and applied
