### ISSUE TITLE
Q: @Mention in Form Webhook

### ISSUE THREAD

**Issue by SimonBondRSA** [Iku/Google-Forms-to-Discord#49]
Hi there,
I tried this according to your previous answer to #11 and, as a newbie non-coder, I would love a specific way to add this! 

Any help is appreciated, thanks!

**Comment by Wqrld** [comment]
grab the group id using discord developer mode and then just add <@role number id here>

**Comment by skybird23333** [comment]
ping a person <@USERID>
ping a role <@&ROLEID>
if you put the ping inside the embed it will not work, make sure its in the content value

**Comment by Wqrld** [comment]
> ping a person <@userid>
> ping a role <@&ROLEID>
> if you put the ping inside the embed it will not work, make sure its in the content value

thanks for the extreme necro, useful for future people i guess :)

**Comment by ToasterBath2** [comment]
has this been solved yet?

**Comment by TheButterZone** [comment]
Yes, scroll up.

**Comment by ToasterBath2** [comment]
Can someone send an example? I don't know how to code very well.

**Comment by skybird23333** [comment]
what do you need to use it for?

ToasterBath2 <notifications@github.com>于2020年6月2日 周二上午8:29写道：

**Comment by TheButterZone** [comment]
> Can someone send an example? I don't know how to code very well.

https://github.com/Iku/Google-Forms-to-Discord/issues/49#issuecomment-611910758

**Comment by skybird23333** [comment]
> ping a person <@USERID>
> 
> ping a role <@&ROLEID>
> 
> if you put the ping inside the embed it will not work, make sure its in the content value

**Comment by FatHyZayed** [comment]
where to put it?

`var POST_URL = "WEBHOOKURL";

function onSubmit(e) {
    var form = FormApp.getActiveForm();
    var allResponses = form.getResponses();
    var latestResponse = allResponses[allResponses.length - 1];
    var response = latestResponse.getItemResponses();
    var items = [];

    for (var i = 0; i < response.length; i++) {
        var question = response[i].getItem().getTitle();
        var answer = response[i].getResponse();
        try {
            var parts = answer.match(/[\s\S]{1,1024}/g) || [];
        } catch (e) {
            var parts = answer;
        }

        if (answer == "") {
            continue;
        }
        for (var j = 0; j < parts.length; j++) {
            if (j == 0) {
                items.push({
                    "name": question,
                    "value": parts[j],
                    "inline": false
                });
            } else {
                items.push({
                    "name": question.concat(" (cont.)"),
                    "value": parts[j],
                    "inline": false
                });
            }
        }
    }

    var options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        },
        "payload": JSON.stringify({
            "content": null, // This is not an empty string
            "embeds": [{
                "title": "TOP TEXT CHANGE THIS IN SCRIPT",
                "fields": items,
                "footer": {
                    "text": "BOTTOM TEXT CHANGE THIS IN SCRIPT"
                }
            }]
        })
    };

    UrlFetchApp.fetch(POST_URL, options);
};`

**Comment by TheButterZone** [comment]
In either place where it says "change this"...

**Comment by Joris-1** [comment]
Thne it doesn't ping, because it's in a embed

**Comment by acollierr17** [comment]
If you update the `content` property, it'll attach an actual message, not embed, along with the embed. Here you can ping roles at your disposal. Example:
```
"payload": JSON.stringify({
        "content": "@Boosters new car video idea", // This is not an empty string
        "embeds": [{
            "title": "TOP TEXT CHANGE THIS IN SCRIPT",
            "fields": items,
            "footer": {
                "text": "BOTTOM TEXT CHANGE THIS IN SCRIPT"
            }
        }]
    })
```
