### ISSUE TITLE
TypeError: Function match in object trifft zu,trifft zu,trifft zu not found

### ISSUE THREAD

**Issue by MrBlue9** [Iku/Google-Forms-to-Discord#5]
When submitting the form and thereby run the script, I get the stated error. The "trifft zu, trifft zu, trifft zu" is coming from a GridItem (https://developers.google.com/apps-script/reference/forms/grid-item) in the form which has three rows with 2 buttons each. I guess the match() function doesn't know how to handle the data it's getting passed. Is there any way around this? Maybe by excluding this answer from matching or something else?

Any help would be greatly appreciated :-)

**Comment by amosharper** [comment]
I worked around this issue by taking `answer` at face value if `answer.match()` fails:

```
try {
      var parts = answer.match(/[\s\S]{1,1024}/g) || [];
    }
    catch (e) {
      var parts = answer;
    }
```

It's far from ideal but it does result in a script that runs to completion rather than throwing an exception and failing.

**Comment by Iku** [comment]
> I worked around this issue by taking `answer` at face value if `answer.match()` fails:
> 
> ```
> try {
>     var parts = answer.match(/[\s\S]{1,1024}/g) || [];
> } catch (e) {
>     var parts = answer;
> }
> ```
> It's far from ideal but it does result in a script that runs to completion rather than throwing an exception and failing.

thanks for that ill lock the convo here and leave it with that for now, the google form api is a struggle.
