### ISSUE TITLE
script error?

### ISSUE THREAD

**Issue by alexjanito** [Iku/Google-Forms-to-Discord#50]
Recently I noticed the form was not posting to discord anymore so I came back to this and as I copied the new code from last month, without changing anything (except the webhook link), I got this error message in the script editor. and its keeping me from saving and continuing, it doesn't work at the moment.

**Missing } after property list. (line 44, file "Code")**

![script](https://user-images.githubusercontent.com/59080400/71236943-3d94f100-22ce-11ea-8755-ac5718c36a11.JPG)

**Comment by Iku** [comment]
this should be fixed
