### ISSUE TITLE
OnSubmit Trigger Problem

### ISSUE THREAD

**Issue by NzTWeber** [Iku/Google-Forms-to-Discord#54]
Can't change "Choose Which function to run" in the current projects trigger's from myFunction to OnSubmit.

**Comment by dctravis** [comment]
I am having the same issue... I am not sure if there is a pre-requisite step needed in order to allow for custom functions and triggers, but this is the only step that I have an issue with while trying to follow the setup. Any help would be appreciated.
![Capture](https://user-images.githubusercontent.com/62796610/77822861-883fb980-70c4-11ea-927c-9e6a797c5228.PNG)

**Comment by NzTWeber** [comment]
Did you figure it out?

**Comment by dctravis** [comment]
Nope, I tried going through the google tutorials and it talks a lot about add-on triggers, but I cant figure out how the hell to add them 🤔

**Comment by NzTWeber** [comment]
just to get this correct you want to add a google form to be sent to a
discord channel correct? if so send me an invite on discord NzTWeber#0001
and ill screenshare with you I ended up figuring it out

**Comment by 3GaNwO** [comment]
I still can't get this to work idk what is going wrong with my setup :(

**Comment by SecretTryhqrd** [comment]
> I still can't get this to work idk what is going wrong with my setup :(

I had this same problem but after examining the code you have to delete the code that states "function Myfunction" at the top so that the code appears like this...
![Github Discord Bot](https://user-images.githubusercontent.com/65322188/81884185-2ac4d680-9565-11ea-9d39-def938ff72c4.PNG)

**Comment by NzTWeber** [comment]
If you have discord send me a DM anytime and lets screen share and get this
working for you NzTWeber#0001

**Comment by SecretTryhqrd** [comment]
No, that’s the solution. There is no problem. The problem was, was that instead of “Function OnSubmit” on top, there was the default “Function myFunction”

**Comment by acollierr17** [comment]
You need to clear the whole file before putting in the new script. Otherwise, the trigger is going to try to run the invalid `myFunction` function instead of the `onSubmit` function.
