### ISSUE TITLE
REQUEST: Display the content of a link? 

### ISSUE THREAD

**Issue by Anh9000** [Iku/Google-Forms-to-Discord#55]
![image](https://user-images.githubusercontent.com/8799430/73772493-3a56a700-474e-11ea-8320-ce2c0a37e1f4.png)

Is there a function line that would allow the link to display a video player or image preview or w/e link is being sent? Just like when someone sends a youtube link on discord?

**Comment by acollierr17** [comment]
Image previews are a thing in embeds. However, video previews aren't. At the most, the thumbnail for a YouTube video or something could be pulled? If image previews are something you would like to see, please, let me know.

**Comment by learfuls** [comment]
> Image previews are a thing in embeds. However, video previews aren't. At the most, the thumbnail for a YouTube video or something could be pulled? If image previews are something you would like to see, please, let me know.

can you reply to my dm on discord
my discord is lear#0001
I need help on setting a preview for the embeds and also need help on making it mention a specific role in my discord server

**Comment by acollierr17** [comment]
> can you reply to my dm on discord
> my discord is lear#0001
> I need help on setting a preview for the embeds and also need help on making it mention a specific role in my discord server
Hi, I have added you back on Discord. Sorry for the initial reply.

**Comment by sswingle142** [comment]
Was this figured out? our form has people paste a picture and we wanted it to show up when the bot posts it but we just get a link
