### ISSUE TITLE
Error 400 Code from Discord

### ISSUE THREAD

**Issue by bdeavilla** [Iku/Google-Forms-to-Discord#56]
Request failed for https://discordapp.com returned code 400. Truncated server response: {"embeds": ["0"]} (use muteHttpExceptions option to examine full response)
    at onSubmit(text:56)

Getting the above error, I believe it may be due to the size out the output.  Is there a way to send multiple messages to split the output?

**Comment by Vanzman** [comment]
I just started receiving this error a couple days ago, previously the script was working without any issues.

**Comment by SyedShad** [comment]
I'm receiving the same error code, It used to work fine before. Any possible solution?

**Comment by acollierr17** [comment]
Is this issue still happening? I am using this script with very little modifications and it's running smoothly?

I have been seeing issues such as #68 and #69 pretty recently, but more feedback would be useful!
