### ISSUE TITLE
TypeError Line #7

### ISSUE THREAD

**Issue by BenTheMiner** [Iku/Google-Forms-to-Discord#57]
Error states: "TypeError: Cannot read property 'getItemResponses' of undefined (line 7, file "Code")"
Line #7 states: "    var response = latestResponse.getItemResponses();"

**Comment by acollierr17** [comment]
That makes the script wasn't able to get the latest response from the form. Is your form set up properly with the script hooked up to it and the trigger running?

More information would be much appreciated!
