### ISSUE TITLE
TypeError: Cannot read property "response" from undefined. (line 4, file "Code")

### ISSUE THREAD

**Issue by Munkeh-** [Iku/Google-Forms-to-Discord#6]
When i change the POST_URL but when you try to run the scrip i get this error "TypeError: Cannot read property "response" from undefined. (line 4, file "Code")"

**Comment by Iku** [comment]
can you give me a screenshot of exactly what you have, sounds like user error.

**Comment by Munkeh-** [comment]
![code](https://user-images.githubusercontent.com/10477519/41085460-04702894-6a2f-11e8-876c-9851612b6c16.png)

There we go uploaded

**Comment by Iku** [comment]
oh, you don't run the script. you set it to trigger on_submit, the response isn't defined because its not running the script after a response has been made to the form. so there is nothing in it. so clicking run will always throw that error

**Comment by Iku** [comment]
simple misunderstanding.
