### ISSUE TITLE
text: Date

### ISSUE THREAD

**Issue by abolyderechte** [Iku/Google-Forms-to-Discord#61]
![image](https://user-images.githubusercontent.com/60314247/79334012-d4418980-7f1f-11ea-93d3-8d3a42082d1e.png)

What do I have to write here, to show the Date, when the Google FOrm was send?

**Comment by acollierr17** [comment]
According to the [Form](https://developers.google.com/apps-script/reference/forms/form-response#gettimestamp) class on Google's [Apps Script](https://developers.google.com/apps-script) API, you can use `<FormResponse>.getTimestamp()` to retrieve the timestamp of the form response.

In this case, remove the `" "` and do `form.getTimestamp()`
```
"footer": {
   "text": form.getTimestamp()
}
```
If you have any issues with this, you may reopen this issue.
