### ISSUE TITLE
How do you add colour to the embed?

### ISSUE THREAD

**Issue by Mystik01** [Iku/Google-Forms-to-Discord#63]

**Comment by Proficus** [comment]
UP

**Comment by Raphilia** [comment]
Add the "color" property below "title":
`            "embeds": [{
                "title": "TOP TEXT CHANGE THIS IN SCRIPT",
                "color" : "decimal_color_here",`
color code must be [decimal](https://www.mathsisfun.com/hexadecimal-decimal-colors.html)
