### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by michaelproductions** [Iku/Google-Forms-to-Discord#69]
thisis not working anymore it doesnt send anything to discord. Try it by yourself

**Comment by acollierr17** [comment]
The webhook is posting perfectly fine for me. Can you go through all the steps you did? Please be descriptive.

**Comment by phiomet** [comment]
It looks like Discord will not accept the answer for longer forms because there are too many characters. Therefore a shortening of the forwarded data would be necessary.
