### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by rajkumargopal** [Iku/Google-Forms-to-Discord#7]
First, let me thank you for the code, it works like a charm.

I have a small request, i would like to display only certain fields in discord and not all fields. Is there a possible way to do that. 

Thanks in Advance

**Comment by TheButterZone** [comment]
I'm wondering this too because I can barely code my way out of a paper bag, let alone do a subtract/exclude function. 

I was able to add to the webhook's embed a link to the spreadsheet that collects form responses, so really, only 2 out of 5 fields from the form submission need to go to Discord.
