### ISSUE TITLE
Still works guys

### ISSUE THREAD

**Issue by Jeydin21** [Iku/Google-Forms-to-Discord#73]
This thing still works, but I just have one question, is there a way to change the color for the embed in Discord to **a RANDOM color**? I want to use multiple colors, just having one color makes It dull, I wanna spice things up a little, you know? Feel free to comment if you have an answer.

**Comment by oranges13** [comment]
It's basically javascript, you could use something like this: https://www.w3resource.com/javascript-exercises/fundamental/javascript-fundamental-exercise-11.php and assign that as the color in the webhook payload.

**Comment by brys0** [comment]
Jeydin check **_pull requests_**

**Comment by Jeydin21** [comment]
Stop stalking me on GitHub brys

**Comment by Jeydin21** [comment]
I already figured out how to do it by reading other issues a long time ago. You must remember that the GoogleBot Moderator Staff Applications had color, right?
